## Generated by graphCompress tool automatically ##
## Compress configuration and fine tuning goal ##
compressConfig = {
  'conv1_2'  : {'algorithm': 'Tucker-2', 'rank': [32, 40]},
  'conv2_1'  : {'algorithm': 'Tucker-2', 'rank': [44, 64]},
  'conv2_2'  : {'algorithm': 'Tucker-2', 'rank': [68, 68]},
  'conv3_1'  : {'algorithm': 'Tucker-2', 'rank': [88, 112]},
  'conv3_2'  : {'algorithm': 'Tucker-2', 'rank': [132, 132]},
  'conv3_3'  : {'algorithm': 'Tucker-2', 'rank': [124, 116]},
  'conv4_1'  : {'algorithm': 'Tucker-2', 'rank': [152, 196]},
  'conv4_2'  : {'algorithm': 'Tucker-2', 'rank': [192, 200]},
  'conv4_3'  : {'algorithm': 'Tucker-2', 'rank': [180, 156]},
  'conv5_1'  : {'algorithm': 'Tucker-2', 'rank': [180, 168]},
  'conv5_2'  : {'algorithm': 'Tucker-2', 'rank': [168, 168]},
  'conv5_3'  : {'algorithm': 'Tucker-2', 'rank': [168, 164]},
  'fc6'  : {'algorithm': 'SVD', 'rank': [596]},
  'fc7'  : {'algorithm': 'SVD', 'rank': [292]},
  'fc8'  : {'algorithm': 'SVD', 'rank': [184]},
}
tuningGoal = [{'accuracy@5': 0.88444, 'loss/loss': 1.3008920161109092, 'accuracy@1': 0.68358}]

## Compress factor and layer factors of this config##
desiredCompressFactor = None
realCompressFactor = 3.00204675002
layerCompressFactor = {
  'conv1_1'  : 1.0,
  'conv1_2'  : 2.28571428571,
  'conv2_1'  : 2.02816901408,
  'conv2_2'  : 2.49823800488,
  'conv3_1'  : 2.29253731343,
  'conv3_2'  : 2.62844919786,
  'conv3_3'  : 3.08976615539,
  'conv4_1'  : 2.89560914304,
  'conv4_2'  : 4.31865042174,
  'conv4_3'  : 5.55452593513,
  'conv5_1'  : 5.23896823705,
  'conv5_2'  : 5.53762956287,
  'conv5_3'  : 5.64489702167,
  'fc6'  : 5.90792417285,
  'fc7'  : 7.01369863014,
  'fc8'  : 4.36830250495,
}
